### ISSUE TITLE
Injection fails with DeploymentException for additional classpaths with spaces in their path

### ISSUE THREAD

**Issue by AdrianoKF** [BrynCooke/cdi-unit#78]
A curious issue occurs when working with additional classpaths that contain spaces in their path.
Tests that run perfectly fine when the project resides under a path without spaces throw a `org.jboss.weld.exceptions.DeploymentException` at runtime as soon as they are moved to a path containing a space character. I am building my project and executing tests using Gradle in a multi-project setup. The issue still occurs with cdi-unit version 3.1.3.

I have prepared a minimal working example on [GitHub](https://github.com/AdrianoKF/cdi-unit-paths).

If you clone this repository into a path without a space, `gradlew clean test` executes without problems. If the path contains a space, the test execution fails with the aforementioned exception. The integration test in the `client` sub-project is adding the classpath for the `service` project, so the `Helper` class should be available for injection into the test class.

**Comment by alien0matic** [comment]
In order to get a URL there has been an URL converted to string, used in a new File object and then converted to a Uri and then URL. The space in the path has been encoded as "%20" right from the start and toUri converts the % to "%25" and then you have "%2520" instead of your space. 
Remove the unnecessary conversions and you are good to go.
